import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

// class item{
//   final String label, images, harga ;
//
//   item({required this.label, required this.images, required this.harga});
// }
//
// List<item> isiItem = [
//   item(label: 'Korean Dress', images: './lib/assets/images/dress.jpeg', harga: 'Rp. 573000'),
//   item(label: 'Cargo Pants', images: './lib/assets/images/pants.jpg', harga: 'Rp. 430000'),
//   item(label: 'Troussers', images: './lib/assets/images/shirt.jpg', harga: 'Rp. 370000'),
//   item(label: 'Nike Air Max 90', images: './lib/assets/images/shoes.png', harga: 'Rp. 790000'),
//   item(label: 'Uniqlo T-Shirt', images: './lib/assets/images/t-shirt.png', harga: 'Rp. 289000'),
//   item(label: 'Twill Cap Uniqlo', images: './lib/assets/images/cap.jpeg', harga: 'Rp. 573000')
// ];

var products = [
  ["Korean Dress","./lib/assets/images/dress.png", "\Rp. 573000", "YUUL YIE", "Bahan kain: Poliester Packing termasuk: Gaun Disarankan untuk memilih sesuai dengan jumlah yard yang biasa Anda pakai. Jika Anda tidak yakin, dalam keadaan normal, Ukuran S cocok untuk orang banyak (40-45 kg) Ukuran M cocok untuk orang banyak (45-50 kg) Ukuran L cocok untuk orang banyak (50-55 kg) Ukuran XL cocok untuk orang banyak (55-60kg) Ukuran 2XL cocok untuk orang banyak (60-65kg) Ukuran grafik: ( Karena pengukuran manual, ada kesalahan 1-3 cm, mohon maafkan saya! ) Ukuran S panjang: 110cm Lingkar Dada 76cm Lingkar pinggang: 68 cm Ukuran M panjang: 111cm Lingkar Dada 80cm Lingkar pinggang: 72 cm Ukuran L panjang: 112 cm Lingkar dada 84 cm Lingkar pinggang: 76 cm Ukuran XL Panjang: 113 cm Lingkar Dada 88 cm Lingkar pinggang: 80 cm Ukuran 2XL Panjang: 114 cm Lingkar Dada 92 cm Lingkar pinggang: 84 cm ( Karena pengukuran manual, ada kesalahan 1-3 cm, mohon maafkan saya! ) Cara Merawat : 1. Jangan mencampur lingerie dengan pakaian berwarna gelap untuk melindungi warna lingerie. 2. Untuk mencuci bahan satin atau sutra, gunakan deterjen ringan atau sabun mandi. 3. Jangan mengeringkan lingerie di mesin pengering. 4. Selalu mencuci dengan air dingin dan bukan air panas. Karena air panas merusak elastisitasnya. 5. Jangan mencuci dengan sikat."],
  ["Cargo Pants", "./lib/assets/images/pants.png", "\Rp. 430000", "AUFCO", "Cargo Long Pants AUFCO di design dengan warna indah dengan kain pilihan yang membuatmu nyaman sepanjang hari.Memiliki resleting, belt loop, 6 saku simpel, 2 di bagian samping depan atas dan bagian bawah di kanan dan kiri, 2 di bagian belakang kanan dan kiri.Bahan : KatunModel Produk : Skinny FitDel Ukuran: (Sesuaikan)S (28)= Lebar Pinggang: 38 cm x Panjang Celana: 98 cmM (30)= Lebar Pinggang: 40 cm x Panjang Celana: 100 cmL (32)= Lebar Pinggang: 42 cm x Panjang Celana: 100 cmXL (34)= Lebar Pinggang: 44 cm x Panjang Celana: 102 cm2XL (36)= Lebar Pinggang: 46 cm x Panjang Celana: 102 cm3XL (38)= Lebar Pinggang: 48 cm x Panjang Celana: 102 cm4XL (40)= Lebar Pinggang: 50 cm x Panjang Celana: 104 cm5XL (42)= Lebar Pinggang: 52 cm x Panjang Celana: 104 cm*Diukur secara manual, toleransi ukuran ± 1-2 cm."],
  ["Troussers", "./lib/assets/images/shirt.png", "\Rp. 370000", "H&M", "Kemeja Regular Fit merupakan long sleeves shirt berbahan Canvas yang di design casual dengan front button opening & two chest pocket sehingga nyaman di gunakan.Size Chart :Size M (Lebar Dada 54 cm x Panjang Baju 74 cm x Panjang Lengan 63 cm x Lebar Bahu 45 cm), Size L (Lebar Dada 56 cm x Panjang Baju 76 cm x Panjang Lengan 64 cm x Lebar Bahu 47 cm), Size XL (Lebar Dada 58 cm x Panjang Baju 76 cm x Panjang Lengan 65 cm x Lebar Bahu 49 cm)  Noted : Tinggi model 186 cm, menggunakan ukuran L. Toleransi ± 1 cm"],
  ["Nike Air Max 90", "./lib/assets/images/shoes.png", "\Rp. 790000", "NIKE", "Clean Lines, Versatile And Timeless—the People’s Shoe Returns With The Nike Air Max 90. Featuring The Same Iconic Waffle Sole, Stitched Overlays And Classic Tpu Accents You’ve Come To Love, It Lets You Walk Among The Pantheon Of Air."],
  ["Uniqlo T-Shirt", "./lib/assets/images/t-shirt.png", "\Rp. 289000", "UNIQLO", "T-shirt Pria dengan potongan oversized. Bahan kasual yang bentuknya tidak mudah berubah setelah dicuci."],
  ["Twill Cap Uniqlo", "./lib/assets/images/cap.png", "\Rp. 135000", "UNIQLO", "Untuk pemilihan warna, ukuran atau type bisa ditulis di catatan ya, Terimakasih ORIGINAL PRODUCT 64% Cotton, 36% Polyester SIZE Around the Head: 59 cm Brim: 7 cm It’s packed with features that are useful for going outside on a hot day. Conveniently designed to be worn with casual or fashionable outfits. It has a heat-shielding effect, so it feels very light and refreshing. The basic design can be used in a variety of ways such as going out on a sunny day, for leisure activities, or as a stylish coordinate. With UV Protection technology."],
  ["Lady D Small Handbag", "./lib/assets/images/diorhandbag.png", "\Rp. 2329000", "DIOR", "The Lady Dior My ABCDior bag epitomizes Dior's vision of elegance and beauty. Sleek and refined, the timeless style is crafted in powder pink lambskin with Cannage stitching, creating the instantly recognizable quilted texture. Pale gold-finish metal D.I.O.R. charms further embellish its silhouette with an elegant touch. Featuring a shoulder strap that can be personalized with badges, the small, unique design may be carried by hand or worn crossbody."],
  ["Pashmina Silk", "./lib/assets/images/pashmina.png", "\Rp. 115000", "CARDENZA", "Pashmina berbahan Silk premium yang dijahit tepi rapi, cocok digunakan di segala acara. Dengan karakteristik bahan yang mengkilap / shiny, membuat elegan dan mewah saat dikenakan. Bahan yang jatuh, halus,  membuat Silk premium lebih banyak diminati sebab mudah dibentuk di wajah.Sangat cocok digunakan sehari - hari atau diacara - acara tertentu, karena kain jenis Silk, memiliki karakteristik yang tidak mudah kusut dan tidak gerah saat dikenakan."],
  ["Ash Blue Dress", "./lib/assets/images/bluedress.png", "\Rp. 559000", "YUUL YIE", "Bahan kain: Poliester Packing termasuk: Gaun Disarankan untuk memilih sesuai dengan jumlah yard yang biasa Anda pakai. Jika Anda tidak yakin, dalam keadaan normal, Ukuran S cocok untuk orang banyak (40-45 kg) Ukuran M cocok untuk orang banyak (45-50 kg) Ukuran L cocok untuk orang banyak (50-55 kg) Ukuran XL cocok untuk orang banyak (55-60kg) Ukuran 2XL cocok untuk orang banyak (60-65kg) Ukuran grafik: ( Karena pengukuran manual, ada kesalahan 1-3 cm, mohon maafkan saya! ) Ukuran S panjang: 110cm Lingkar Dada 76cm Lingkar pinggang: 68 cm Ukuran M panjang: 111cm Lingkar Dada 80cm Lingkar pinggang: 72 cm Ukuran L panjang: 112 cm Lingkar dada 84 cm Lingkar pinggang: 76 cm Ukuran XL Panjang: 113 cm Lingkar Dada 88 cm Lingkar pinggang: 80 cm Ukuran 2XL Panjang: 114 cm Lingkar Dada 92 cm Lingkar pinggang: 84 cm ( Karena pengukuran manual, ada kesalahan 1-3 cm, mohon maafkan saya! ) Cara Merawat : 1. Jangan mencampur lingerie dengan pakaian berwarna gelap untuk melindungi warna lingerie. 2. Untuk mencuci bahan satin atau sutra, gunakan deterjen ringan atau sabun mandi. 3. Jangan mengeringkan lingerie di mesin pengering. 4. Selalu mencuci dengan air dingin dan bukan air panas. Karena air panas merusak elastisitasnya. 5. Jangan mencuci dengan sikat."],
  ["Knit Sweater", "./lib/assets/images/knitsweater.png", "\Rp. 229000", "BNB", "Casual Oversized Striped Pullovers Women Knitted Basic Autumn Winter Loose-Fitting Thick Jumpers Sweaters Female Clothing"],
];

// var carts = [
//
// ];